# Generated by Django 5.1.3 on 2024-12-23 09:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('animal_type', models.CharField(choices=[('dog', 'Dog'), ('cat', 'Cat'), ('bird', 'Bird'), ('fish', 'Fish'), ('small_pet', 'Small Pet'), ('other', 'Other')], max_length=20)),
                ('stock', models.IntegerField(default=0)),
                ('specifications', models.JSONField(blank=True, default=dict, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='categories.category')),
            ],
            options={
                'db_table': 'products',
                'indexes': [models.Index(fields=['animal_type'], name='products_animal__4a32d7_idx'), models.Index(fields=['category'], name='products_categor_4083ff_idx'), models.Index(fields=['name'], name='products_name_6f9890_idx')],
            },
        ),
    ]
